use serde::{Deserialize, Serialize};

use super::skill_model::Skill;

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct User {
    pub name: Option<String>,
    pub username: String, // mandatory
    pub password: String, //mandatory
    pub email: Option<String>,
    pub role: Option<i32>,
    pub field: Option<String>, // 0..2 -> 0:Admin, 1:Teacher, 2:Guest
    pub completed_skills: Option<Vec<Skill>>, //unaccessible if role > 1
    pub auth_token: Option<String>, //generated by backend
    pub active: Option<bool>,
}
