[package]
name = "Fiesta-Server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# To add other dependencies, add them in the format stated below.
[dependencies]
rocket = "0.5.0-rc.2"