# defaults for _all_ profiles
[default]
address = "127.0.0.1"

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
port = 4200


## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]
port = 4200
