name: Rust

on:
  push:
    branches: [ "masta" ]
  pull_request:
    branches: [ "masta" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd Fiesta-Server && cargo build --verbose
    - name: Run tests
      run: cd Fiesta-Server && cargo test --verbose
