name: Rust

on:
  push:
    branches: [ "masta" ]
  pull_request:
    branches: [ "masta" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd Fiesta-Server && rustup override set nightly && cargo build --verbose
    - name: Build
      run: ls -Ra
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifact
        path: Fiesta-Server/target/debug/fiesta_server
      
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd Fiesta-Server && rustup override set nightly && cargo test --verbose
